CREATE TABLE lists(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL,
    name TEXT,
    note TEXT,
    price NUMERIC,
    weight NUMERIC,
    start_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    completed_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    checked BOOLEAN NOT NULL,
    user_id INTEGER 
        REFERENCES users(id) ON DELETE CASCADE
);